<a href="https://colab.research.google.com/github/Mahammad-Haroon/Data-Analysis-Projects/blob/main/CityRide_Missing_Data_Imputation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# CityRide Data Cleaning and Imputation
### Missing Data Strategy and Impact Analysis

## Step 0: Generate Dataset

In [1]:
import pandas as pd
import numpy as np

np.random.seed(42)

n = 200

df = pd.DataFrame({
    "Ride_ID": [f"RIDE_{i+1}" for i in range(n)],
    "Ride_Distance": np.random.normal(8, 2.5, n).round(2),
    "Fare_Amount": np.random.normal(250, 80, n).round(2),
    "Driver_Rating": np.random.choice([3, 4, 5, np.nan], size=n, p=[0.2, 0.2, 0.12, 0.48]),
    "Vehicle_Type": np.random.choice(["Sedan", "SUV", "Mini", np.nan], size=n, p=[0.3, 0.3, 0.34, 0.06]),
    "Outside_Temperature": np.random.normal(30, 4, n).round(1),
    "Ride_Time": pd.date_range(start="2023-01-01", periods=n, freq="H")
})

# Introduce additional missingness
df.loc[df.sample(frac=0.03).index, "Ride_Distance"] = np.nan
df.loc[df.sample(frac=0.01).index, "Fare_Amount"] = np.nan
df.loc[df.sample(frac=0.12).index, "Outside_Temperature"] = np.nan

df.head()

/tmp/ipykernel_184/2997814897.py:15: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  "Ride_Time": pd.date_range(start="2023-01-01", periods=n, freq="H")

,Ride_ID,Ride_Distance,Fare_Amount,Driver_Rating,Vehicle_Type,Outside_Temperature,Ride_Time
0,RIDE_1,9.24,278.62,5.0,Sedan,31.2,2023-01-01 00:00:00
1,RIDE_2,7.65,294.86,4.0,Mini,23.2,2023-01-01 01:00:00
2,RIDE_3,9.62,NaN,3.0,Sedan,24.6,2023-01-01 02:00:00
3,RIDE_4,11.81,334.30,NaN,Sedan,33.0,2023-01-01 03:00:00
4,RIDE_5,7.41,139.79,NaN,Sedan,30.7,2023-01-01 04:00:00

## Task 1: Missing Data Assessment

In [2]:
missing_percent = (df.isnull().sum() / len(df)) * 100
missing_percent

Ride_ID                 0.0
Ride_Distance           3.0
Fare_Amount             1.0
Driver_Rating          43.0
Vehicle_Type            0.0
Outside_Temperature    12.0
Ride_Time               0.0
dtype: float64

In [3]:
strategy_table = pd.DataFrame({
    "Column": df.columns,
    "Data_Type": df.dtypes.values,
    "Percent_Missing": missing_percent.values,
    "Chosen_Strategy": [
        "None",
        "Median",
        "Mean",
        "Flag_and_Zero",
        "Mode",
        "Forward_Fill",
        "None"
    ]
})

strategy_table

                Column       Data_Type  Percent_Missing Chosen_Strategy
0              Ride_ID          object              0.0            None
1        Ride_Distance         float64              3.0          Median
2          Fare_Amount         float64              1.0            Mean
3        Driver_Rating         float64             43.0   Flag_and_Zero
4         Vehicle_Type          object              0.0            Mode
5  Outside_Temperature         float64             12.0    Forward_Fill
6            Ride_Time  datetime64[ns]              0.0            None

## Task 2: Apply Imputation Strategies

In [4]:
original_df = df.copy()

In [5]:
df["Ride_Distance"].fillna(df["Ride_Distance"].median(), inplace=True)

/tmp/ipykernel_184/1263239205.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Ride_Distance"].fillna(df["Ride_Distance"].median(), inplace=True)

In [6]:
df["Fare_Amount"].fillna(df["Fare_Amount"].mean(), inplace=True)

/tmp/ipykernel_184/1054467543.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Fare_Amount"].fillna(df["Fare_Amount"].mean(), inplace=True)

In [7]:
df["Vehicle_Type"].fillna(df["Vehicle_Type"].mode()[0], inplace=True)

/tmp/ipykernel_184/2499685932.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Vehicle_Type"].fillna(df["Vehicle_Type"].mode()[0], inplace=True)

In [8]:
df = df.sort_values("Ride_Time")

In [9]:
df["Outside_Temperature"].fillna(method="ffill", inplace=True)

/tmp/ipykernel_184/1317836309.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Outside_Temperature"].fillna(method="ffill", inplace=True)
/tmp/ipykernel_184/1317836309.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["Outside_Temperature"].fillna(method="ffill", inplace=True)

In [10]:
df["Outside_Temperature"].fillna(method="ffill", inplace=True)

/tmp/ipykernel_184/1317836309.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Outside_Temperature"].fillna(method="ffill", inplace=True)
/tmp/ipykernel_184/1317836309.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["Outside_Temperature"].fillna(method="ffill", inplace=True)

In [11]:
df["Driver_Rating"].fillna(0, inplace=True)

/tmp/ipykernel_184/479317378.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Driver_Rating"].fillna(0, inplace=True)

In [12]:
comparison = pd.DataFrame({
    "Original_Nulls": original_df.isnull().sum(),
    "Cleaned_Nulls": df.isnull().sum()
})

comparison

                     Original_Nulls  Cleaned_Nulls
Ride_ID                           0              0
Ride_Distance                     6              0
Fare_Amount                       2              0
Driver_Rating                    86              0
Vehicle_Type                      0              0
Outside_Temperature              24              0
Ride_Time                         0              0

## Task 3: Behavioral Impact Analysis

In [14]:
df["Driver_Rating_Missing"] = df["Driver_Rating"].isnull().astype(int)

In [15]:
df["Driver_Rating"].fillna(0, inplace=True)

/tmp/ipykernel_184/479317378.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Driver_Rating"].fillna(0, inplace=True)

In [16]:
avg_missing = df[df["Driver_Rating_Missing"] == 1]["Fare_Amount"].mean()
avg_missing

nan

In [17]:
avg_not_missing = df[df["Driver_Rating_Missing"] == 0]["Fare_Amount"].mean()
avg_not_missing

np.float64(256.62641414141416)

In [18]:
analysis_table = pd.DataFrame({
    "Group": ["Missing Rating", "Non-Missing Rating"],
    "Average_Fare": [avg_missing, avg_not_missing],
    "Ride_Count": [
        df[df["Driver_Rating_Missing"] == 1].shape[0],
        df[df["Driver_Rating_Missing"] == 0].shape[0]
    ]
})

analysis_table

                Group  Average_Fare  Ride_Count
0      Missing Rating           NaN           0
1  Non-Missing Rating    256.626414         200

In [19]:
df.head()

,Ride_ID,Ride_Distance,Fare_Amount,Driver_Rating,Vehicle_Type,Outside_Temperature,Ride_Time,Driver_Rating_Missing
0,RIDE_1,9.24,278.620000,5.0,Sedan,31.2,2023-01-01 00:00:00,0
1,RIDE_2,7.65,294.860000,4.0,Mini,23.2,2023-01-01 01:00:00,0
2,RIDE_3,9.62,256.626414,3.0,Sedan,24.6,2023-01-01 02:00:00,0
3,RIDE_4,11.81,334.300000,0.0,Sedan,33.0,2023-01-01 03:00:00,0
4,RIDE_5,7.41,139.790000,0.0,Sedan,30.7,2023-01-01 04:00:00,0