<a href="https://colab.research.google.com/github/Mahammad-Haroon/Data-Analysis-Projects/blob/main/Data_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

data = {
    'Customer_ID': [1, 2, 3, 4, 5, 6, 8, 9, 10],
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace', 'Heidi', 'Ivan'],
    'Age': [25, np.nan, 30, 22, 45, np.nan, 33, 38, np.nan],
    'City': ['New York', 'London', np.nan, 'London', 'Paris', 'New York', 'London', np.nan, 'Paris'],
    'Spend_Amount': [150, 200, 120, np.nan, 300, 180, np.nan, 210, 190],
    'Feedback_Notes': [np.nan, np.nan, np.nan, np.nan, np.nan, np.nan, np.nan, np.nan, np.nan]
}

df = pd.DataFrame(data)

df

   Customer_ID     Name   Age      City  Spend_Amount  Feedback_Notes
0            1    Alice  25.0  New York         150.0             NaN
1            2      Bob   NaN    London         200.0             NaN
2            3  Charlie  30.0       NaN         120.0             NaN
3            4    David  22.0    London           NaN             NaN
4            5      Eve  45.0     Paris         300.0             NaN
5            6    Frank   NaN  New York         180.0             NaN
6            8    Grace  33.0    London           NaN             NaN
7            9    Heidi  38.0       NaN         210.0             NaN
8           10     Ivan   NaN     Paris         190.0             NaN

In [ ]:
df.head()

   Customer_ID     Name   Age      City  Spend_Amount  Feedback_Notes
0            1    Alice  25.0  New York         150.0             NaN
1            2      Bob   NaN    London         200.0             NaN
2            3  Charlie  30.0       NaN         120.0             NaN
3            4    David  22.0    London           NaN             NaN
4            5      Eve  45.0     Paris         300.0             NaN

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Customer_ID     9 non-null      int64
 1   Name            9 non-null      object
 2   Age             6 non-null      float64
 3   City            7 non-null      object
 4   Spend_Amount    7 non-null      float64
 5   Feedback_Notes  0 non-null      float64
dtypes: float64(3), int64(1), object(2)
memory usage: 564.0+ bytes

In [ ]:
df.isnull().sum()

Customer_ID       0
Name              0
Age               3
City              2
Spend_Amount      2
Feedback_Notes    9
dtype: int64

Cleaning Strategy:

1. The 'Feedback_Notes' column will be dropped entirely because it contains 100% missing values and provides no useful information.

2. For the 'Age' column, I will use the Mean to fill missing values. There are no extreme outliers in the dataset, so the mean provides a fair estimate.

3. For the 'City' column, I will use the Mode (most frequent city) to fill missing values because it is categorical data.

In [ ]:
df.dropna(axis=1, how='all', inplace=True)

Fill Age with Mean

In [ ]:
age_mean = df['Age'].mean()
df['Age'] = df['Age'].fillna(age_mean)

In [ ]:
age_mean

np.float64(32.166666666666664)

Fill City with Mode

In [ ]:
city_mode = df['City'].mode()[0]
df['City'] = df['City'].fillna(city_mode)

Drop Rows Where Spend_Amount is Missing

In [ ]:
df.dropna(subset=['Spend_Amount'], inplace=True)

Final Null Check

In [ ]:
df.isnull().sum()

Customer_ID     0
Name            0
Age             0
City            0
Spend_Amount    0
dtype: int64

In [ ]:
df.shape

(7, 5)