<a href="https://colab.research.google.com/github/Mahammad-Haroon/Data-Analysis-Projects/blob/main/Data_Cleaning_%E2%80%93_Retail_Sales_Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Objective:** Clean a messy retail sales dataset using Pandas for accurate analysis.

Load the Dataset

In [1]:
import pandas as pd
import io

csv_data = """ Order ID , Region ,Category , Sales , Quantity , Order Date
1001 , north , Electronics , "$1,200" , 10 units , 01-01-2024
1002 , South, electronics , "$850" , 5 Units , 02-01-2024
1003 , EAST , Furniture , "$2,500" , 3 units , 03-01-2024
1004 , west , furnture , "$1,750" , 2 units , 04-01-2024
1005 , Noth , Electronics , "$1,200" , 10 units , 01-01-2024
1005 , Noth , Electronics , "$1,200" , 10 units , 01-01-2024
1006 , south , Office Supplies , "$300" , 7 units , 05-01-2024
1007 , East , office supplies , "$450" , 4 Units , 06-01-2024
1008 , WEST , Electronics , "$1,100" , 6 units , 07-01-2024
"""

df = pd.read_csv(io.StringIO(csv_data), skipinitialspace=True)

print("Initial Dataset")
df.head()

Initial Dataset

   Order ID  Region      Category    Sales   Quantity   Order Date
0       1001  north   Electronics   $1,200   10 units   01-01-2024
1       1002   South  electronics     $850    5 Units   02-01-2024
2       1003   EAST     Furniture   $2,500    3 units   03-01-2024
3       1004   west      furnture   $1,750    2 units   04-01-2024
4       1005   Noth   Electronics   $1,200   10 units   01-01-2024

Inspect Dataset

## Inspecting Dataset
Checking column names, data types, and duplicates.

In [2]:
print("Column Names:")
print(df.columns)

print("\nDataset Info:")
df.info()

Column Names:
Index(['Order ID ', 'Region ', 'Category ', 'Sales ', 'Quantity ',
       'Order Date'],
      dtype='object')

Dataset Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Order ID    9 non-null      int64
 1   Region      9 non-null      object
 2   Category    9 non-null      object
 3   Sales       9 non-null      object
 4   Quantity    9 non-null      object
 5   Order Date  9 non-null      object
dtypes: int64(1), object(5)
memory usage: 564.0+ bytes

This shows:

spaces in column names

incorrect data types

## Task 1 – Fix Structural Issues

1. Remove whitespace from column names
2. Convert column names to Title Case
3. Remove duplicate rows

In [3]:
# Remove spaces from column names
df.columns = df.columns.str.strip()

# Convert column names to Title Case
df.columns = df.columns.str.title()

# Remove duplicate rows
df = df.drop_duplicates()

df.head()

   Order Id  Region      Category    Sales   Quantity  Order Date
0      1001  north   Electronics   $1,200   10 units   01-01-2024
1      1002   South  electronics     $850    5 Units   02-01-2024
2      1003   EAST     Furniture   $2,500    3 units   03-01-2024
3      1004   west      furnture   $1,750    2 units   04-01-2024
4      1005   Noth   Electronics   $1,200   10 units   01-01-2024

## Task 2 – Clean Region Column
- Remove spaces
- Convert to Title Case
- Fix typo "Noth"

In [4]:
df['Region'] = df['Region'].str.strip()
df['Region'] = df['Region'].str.title()

# Fix typo
df['Region'] = df['Region'].replace("Noth","North")

df['Region'].value_counts()

Region
North    2
South    2
East     2
West     2
Name: count, dtype: int64

## Task 3 – Clean Category Column
Standardizing category names and fixing spelling errors.

In [5]:
df['Category'] = df['Category'].str.strip()
df['Category'] = df['Category'].str.title()

# Fix typo
df['Category'] = df['Category'].replace("Furnture","Furniture")

df['Category'].value_counts()

Category
Electronics        4
Furniture          2
Office Supplies    2
Name: count, dtype: int64

## Task 4 – Clean Sales Column
Removing currency symbols and converting to float.

In [6]:
df['Sales'] = df['Sales'].str.replace('$','', regex=False)
df['Sales'] = df['Sales'].str.replace(',','', regex=False)

df['Sales'] = df['Sales'].astype(float)

df[['Sales']].head()

    Sales
0  1200.0
1   850.0
2  2500.0
3  1750.0
4  1200.0

## Task 5 – Clean Quantity Column
Removing unit text and converting to integer.

In [7]:
df['Quantity'] = df['Quantity'].str.lower()
df['Quantity'] = df['Quantity'].str.replace('units','', regex=False)

df['Quantity'] = df['Quantity'].astype(int)

df[['Quantity']].head()

   Quantity
0        10
1         5
2         3
3         2
4        10

## Task 6 – Convert Order Date to Datetime

In [8]:
df['Order Date'] = pd.to_datetime(df['Order Date'], dayfirst=True)

df[['Order Date']].head()

  Order Date
0 2024-01-01
1 2024-01-02
2 2024-01-03
3 2024-01-04
4 2024-01-01

## Final Clean Dataset

In [9]:
df

   Order Id Region         Category   Sales  Quantity Order Date
0      1001  North      Electronics  1200.0        10 2024-01-01
1      1002  South      Electronics   850.0         5 2024-01-02
2      1003   East        Furniture  2500.0         3 2024-01-03
3      1004   West        Furniture  1750.0         2 2024-01-04
4      1005  North      Electronics  1200.0        10 2024-01-01
6      1006  South  Office Supplies   300.0         7 2024-01-05
7      1007   East  Office Supplies   450.0         4 2024-01-06
8      1008   West      Electronics  1100.0         6 2024-01-07

## Final Validation
Checking data types after cleaning.

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8 entries, 0 to 8
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Order Id    8 non-null      int64
 1   Region      8 non-null      object
 2   Category    8 non-null      object
 3   Sales       8 non-null      float64
 4   Quantity    8 non-null      int64
 5   Order Date  8 non-null      datetime64[ns]
dtypes: datetime64[ns](1), float64(1), int64(2), object(2)
memory usage: 748.0+ bytes

## Export Clean Dataset

In [11]:
df.to_csv("clean_sales_data.csv", index=False)