<a href="https://colab.research.google.com/github/Mahammad-Haroon/Data-Analysis-Projects/blob/main/EDA_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# UrbanKart Sales Data Analysis
### By: Haroon Muhammed

In [3]:
import pandas as pd
import numpy as np

np.random.seed(42)

n = 1000  # number of records

df = pd.DataFrame({
    'Order_ID': range(1, n+1),
    'Order_Date': pd.date_range(start='2023-01-01', periods=n, freq='D'),
    'Region': np.random.choice(['North', 'South', 'East', 'West'], n),
    'Category': np.random.choice(['Electronics', 'Clothing', 'Furniture'], n),
    'Customer_Segment': np.random.choice(['Consumer', 'Corporate', 'Home Office'], n),
    'Sales': np.random.randint(100, 20000, n),
    'Discount': np.round(np.random.uniform(0, 0.4, n), 2),
    'Profit': np.random.randint(-2000, 5000, n),
    'Delivery_Days': np.random.randint(1, 12, n),
    'Payment_Mode': np.random.choice(['Cash', 'Card', 'UPI'], n),
    'Customer_Rating': np.random.randint(1, 6, n)
})

# Save dataset
df.to_csv('urbankart_transactions.csv', index=False)

df.head()

,Order_ID,Order_Date,Region,Category,Customer_Segment,Sales,Discount,Profit,Delivery_Days,Payment_Mode,Customer_Rating
0,1,2023-01-01,East,Clothing,Consumer,9064,0.23,-1693,8,UPI,2
1,2,2023-01-02,West,Furniture,Consumer,6593,0.36,1416,4,UPI,4
2,3,2023-01-03,North,Electronics,Consumer,10859,0.38,3246,8,Cash,4
3,4,2023-01-04,East,Electronics,Corporate,5539,0.17,4056,10,Cash,5
4,5,2023-01-05,East,Electronics,Consumer,14573,0.15,334,10,UPI,1

In [4]:
import os
os.listdir()

['.config', 'urbankart_transactions.csv', 'sample_data']

In [5]:
df = pd.read_csv('urbankart_transactions.csv')
df.head()

,Order_ID,Order_Date,Region,Category,Customer_Segment,Sales,Discount,Profit,Delivery_Days,Payment_Mode,Customer_Rating
0,1,2023-01-01,East,Clothing,Consumer,9064,0.23,-1693,8,UPI,2
1,2,2023-01-02,West,Furniture,Consumer,6593,0.36,1416,4,UPI,4
2,3,2023-01-03,North,Electronics,Consumer,10859,0.38,3246,8,Cash,4
3,4,2023-01-04,East,Electronics,Corporate,5539,0.17,4056,10,Cash,5
4,5,2023-01-05,East,Electronics,Consumer,14573,0.15,334,10,UPI,1

In [6]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_ID          1000 non-null   int64
 1   Order_Date        1000 non-null   object
 2   Region            1000 non-null   object
 3   Category          1000 non-null   object
 4   Customer_Segment  1000 non-null   object
 5   Sales             1000 non-null   int64
 6   Discount          1000 non-null   float64
 7   Profit            1000 non-null   int64
 8   Delivery_Days     1000 non-null   int64
 9   Payment_Mode      1000 non-null   object
 10  Customer_Rating   1000 non-null   int64
dtypes: float64(1), int64(5), object(5)
memory usage: 86.1+ KB

,Order_ID,Sales,Discount,Profit,Delivery_Days,Customer_Rating
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,500.500000,10115.446000,0.208030,1510.061000,6.041000,2.961000
std,288.819436,5740.642503,0.113719,2008.755404,3.168811,1.411904
min,1.000000,124.000000,0.000000,-1989.000000,1.000000,1.000000
25%,250.750000,5271.750000,0.110000,-227.000000,3.000000,2.000000
50%,500.500000,10280.500000,0.210000,1564.000000,6.000000,3.000000
75%,750.250000,15163.750000,0.310000,3252.500000,9.000000,4.000000
max,1000.000000,19973.000000,0.400000,4999.000000,11.000000,5.000000

In [7]:
df['Order_Date'] = pd.to_datetime(df['Order_Date'])

In [8]:
df.isnull().sum()

Order_ID            0
Order_Date          0
Region              0
Category            0
Customer_Segment    0
Sales               0
Discount            0
Profit              0
Delivery_Days       0
Payment_Mode        0
Customer_Rating     0
dtype: int64

In [9]:
# Example
df['Sales'].fillna(df['Sales'].median(), inplace=True)
df['Profit'].fillna(df['Profit'].median(), inplace=True)
df['Customer_Rating'].fillna(df['Customer_Rating'].mode()[0], inplace=True)

/tmp/ipykernel_16565/798461161.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Sales'].fillna(df['Sales'].median(), inplace=True)
/tmp/ipykernel_16565/798461161.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Profit'].fillna(df['Profit'].median(), inplace=True)
/tmp/ipykernel_16565/798461161.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Customer_Rating'].fillna(df['Customer_Rating'].mode()[0], inplace=True)

In [10]:
df['Region'] = df['Region'].str.lower().str.strip()
df['Payment_Mode'] = df['Payment_Mode'].str.lower().str.strip()

In [11]:
Q1 = df['Sales'].quantile(0.25)
Q3 = df['Sales'].quantile(0.75)
IQR = Q3 - Q1

outliers = df[(df['Sales'] < Q1 - 1.5*IQR) | (df['Sales'] > Q3 + 1.5*IQR)]
len(outliers)

0

In [12]:
df['Sales'].skew()
df['Profit'].skew()

np.float64(-0.032199837146085694)

In [13]:
df['Sales'].mean(), df['Sales'].median()
df['Profit'].mean(), df['Profit'].median()

(np.float64(1510.061), 1564.0)

In [14]:
std_sales = df['Sales'].std()
mean_sales = df['Sales'].mean()
cv = std_sales / mean_sales

std_sales, cv

(5740.642503015789, np.float64(0.5675125449748621))

In [15]:
import scipy.stats as stats
import numpy as np

mean = df['Profit'].mean()
std = df['Profit'].std()
n = len(df)

ci = stats.t.interval(0.95, n-1, loc=mean, scale=std/np.sqrt(n))
ci

(np.float64(1385.4083148977452), np.float64(1634.7136851022547))

In [16]:
df[['Sales','Profit','Discount','Delivery_Days','Customer_Rating']].corr()

                    Sales    Profit  Discount  Delivery_Days  Customer_Rating
Sales            1.000000 -0.033830 -0.039113      -0.003720        -0.025090
Profit          -0.033830  1.000000 -0.048225      -0.037481        -0.002635
Discount        -0.039113 -0.048225  1.000000      -0.010831         0.005693
Delivery_Days   -0.003720 -0.037481 -0.010831       1.000000        -0.015751
Customer_Rating -0.025090 -0.002635  0.005693      -0.015751         1.000000

In [17]:
df['Sales'].corr(df['Discount'])

np.float64(-0.039112740369821916)

In [18]:
df['Sales'].corr(df['Profit'])

np.float64(-0.033830201937419195)

In [19]:
df['Delivery_Days'].corr(df['Customer_Rating'])

np.float64(-0.015751138191989988)

In [20]:
grouped = df.groupby(['Region','Category','Customer_Segment']).agg({
    'Sales':['mean','median'],
    'Profit':'mean',
    'Order_ID':'count'
}).reset_index()

grouped

   Region     Category Customer_Segment         Sales                Profit  \
                                                 mean   median         mean
0    east     Clothing         Consumer   9076.692308   9132.5  1464.384615
1    east     Clothing        Corporate   9825.000000   9340.5  2180.400000
2    east     Clothing      Home Office  11314.416667  10472.0  1777.416667
3    east  Electronics         Consumer  11395.636364  10410.0  1976.318182
4    east  Electronics        Corporate   8882.560976   9618.0  1193.000000
5    east  Electronics      Home Office  10690.925926  10503.0  1453.777778
6    east    Furniture         Consumer  10276.428571  10388.0  1001.285714
7    east    Furniture        Corporate   9572.312500   8866.0  1544.781250
8    east    Furniture      Home Office  11081.473684  11631.0  1739.421053
9   north     Clothing         Consumer  11246.161290  11695.0  1442.903226
10  north     Clothing        Corporate   9439.868421  10399.0  1543.315789
11  north     Clothing      Home Office  10929.843750  11559.0  1709.093750
12  north  Electronics         Consumer   9943.815789  10455.0  1743.552632
13  north  Electronics        Corporate  10974.111111   9814.0  1559.185185
14  north  Electronics      Home Office  11627.111111  12978.0   870.722222
15  north    Furniture         Consumer  10132.240000  11838.0  1238.000000
16  north    Furniture        Corporate  12765.000000  13082.0  1286.793103
17  north    Furniture      Home Office  11620.750000  13141.5  1686.250000
18  south     Clothing         Consumer   7470.434783   5945.0  1917.434783
19  south     Clothing        Corporate   9019.250000   7154.0  1352.083333
20  south     Clothing      Home Office  11532.375000  11770.0  1671.458333
21  south  Electronics         Consumer  10983.360000  11665.0  2013.720000
22  south  Electronics        Corporate  10395.217391  11340.0  1163.652174
23  south  Electronics      Home Office  11702.875000  12547.5  1395.166667
24  south    Furniture         Consumer   8861.387097   7697.0  2370.612903
25  south    Furniture        Corporate   9036.133333   8780.5  2002.933333
26  south    Furniture      Home Office  10707.769231  10990.5  1311.076923
27   west     Clothing         Consumer   9432.031250   9465.0  1749.437500
28   west     Clothing        Corporate  10519.111111  10202.0  1600.259259
29   west     Clothing      Home Office   9886.966667  10594.0  1755.033333
30   west  Electronics         Consumer  10310.162162   9687.0   987.972973
31   west  Electronics        Corporate   7775.920000   6619.0   944.160000
32   west  Electronics      Home Office  10116.147059   9943.5   916.558824
33   west    Furniture         Consumer   9532.428571   9979.0  1995.228571
34   west    Furniture        Corporate   8761.535714   9357.0   807.928571
35   west    Furniture      Home Office   9803.500000  10384.5  1123.250000

   Order_ID
      count
0        26
1        20
2        24
3        22
4        41
5        27
6        21
7        32
8        19
9        31
10       38
11       32
12       38
13       27
14       18
15       25
16       29
17       20
18       23
19       24
20       24
21       25
22       23
23       24
24       31
25       30
26       26
27       32
28       27
29       30
30       37
31       25
32       34
33       35
34       28
35       32

In [21]:
global_sales = df['Sales'].mean()
global_profit = df['Profit'].mean()

In [22]:
grouped[grouped[('Sales','mean')] > global_sales]
grouped[grouped[('Profit','mean')] < global_profit]

   Region     Category Customer_Segment         Sales                Profit  \
                                                 mean   median         mean
0    east     Clothing         Consumer   9076.692308   9132.5  1464.384615
4    east  Electronics        Corporate   8882.560976   9618.0  1193.000000
5    east  Electronics      Home Office  10690.925926  10503.0  1453.777778
6    east    Furniture         Consumer  10276.428571  10388.0  1001.285714
9   north     Clothing         Consumer  11246.161290  11695.0  1442.903226
14  north  Electronics      Home Office  11627.111111  12978.0   870.722222
15  north    Furniture         Consumer  10132.240000  11838.0  1238.000000
16  north    Furniture        Corporate  12765.000000  13082.0  1286.793103
19  south     Clothing        Corporate   9019.250000   7154.0  1352.083333
22  south  Electronics        Corporate  10395.217391  11340.0  1163.652174
23  south  Electronics      Home Office  11702.875000  12547.5  1395.166667
26  south    Furniture      Home Office  10707.769231  10990.5  1311.076923
30   west  Electronics         Consumer  10310.162162   9687.0   987.972973
31   west  Electronics        Corporate   7775.920000   6619.0   944.160000
32   west  Electronics      Home Office  10116.147059   9943.5   916.558824
34   west    Furniture        Corporate   8761.535714   9357.0   807.928571
35   west    Furniture      Home Office   9803.500000  10384.5  1123.250000

   Order_ID
      count
0        26
4        41
5        27
6        21
9        31
14       18
15       25
16       29
19       24
22       23
23       24
26       26
30       37
31       25
32       34
34       28
35       32